### ISSUE TITLE
Calling igraph::edge_betweenness() on a graph where all edge weights are zeros will be disallowed from igraph 1.2.7

### ISSUE THREAD

**Issue by ntamas** [sysbiolab/TreeAndLeaf#3]
We are preparing the next patch release of `igraph`'s R interface and as we were doing reverse-dependency checks before submission, we noticed that `TreeAndLeaf` calls igraph's `edge_betweenness()` function on a graph where the weights of all edges are zeros. This is disallowed in igraph's C core as the shortest paths are not well-defined in a graph where all weights are zeros (essentially any simple or non-simple path from any node to any other node is a shortest path).

The issue can be fixed easily with the following patch, but I am not familar with the algorithm well enough to judge whether this was the original intention or not:

```patch
diff --git a/R/treeAndLeaf.R b/R/treeAndLeaf.R
index 479d03a..5fa00f6 100644
--- a/R/treeAndLeaf.R
+++ b/R/treeAndLeaf.R
@@ -66,7 +66,7 @@ treeAndLeaf <- function(obj){
     V(gg)$isLeaf <- V(gg)$name%in%coords$phylo$tip.label
     gg$centralVertex <- coords$centralVertex
     #--- set edge weights
-    E(gg)$weight <- 0
+    E(gg)$weight <- 1
     bt <- igraph::edge_betweenness(gg, directed = T)
     bt <- (1 - bt/max(bt))
     E(gg)$weight <- bt
```

**Comment by milena-andreuzo** [comment]
https://github.com/sysbiolab/TreeAndLeaf/commit/7ea90400b10199518cc22ec6ad1075acefdd1550
